// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Test3 {
    private WebDriver driver;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
        driver = new ChromeDriver();
    }
    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void QautoTeest() throws InterruptedException {
        driver.get("https://guest:welcome2qauto@qauto2.forstudy.space/");
        driver.manage().window().setSize(new Dimension(1200, 757));
        driver.findElement(By.className("hero-descriptor_btn")).click();
        driver.findElement(By.id("signupName")).sendKeys("Andrii");
        driver.findElement(By.id("signupLastName")).sendKeys("Wer");
        driver.findElement(By.id("signupEmail")).sendKeys("morannon21@gmail.com");
        driver.findElement(By.id("signupPassword")).sendKeys("kMBBP0ZnbHUEJwB");
        driver.findElement(By.id("signupRepeatPassword")).sendKeys("kMBBP0ZnbHUEJwB");

        driver.findElement(By.cssSelector(".btn-primary:nth-child(1)")).click();
        Thread.sleep(2000);

        driver.findElement(By.xpath("(//a[contains(text(),'Profile')])[2]")).click();

        Thread.sleep(2000);
        assertEquals("Andrii undefined", driver.findElement(By.className("profile_name")).getText());

        driver.findElement(By.cssSelector("a.btn.btn-white.btn-sidebar.sidebar_btn[href='/panel/garage']")).click();
        Thread.sleep(2000);


        driver.findElement(By.cssSelector(".btn.btn-primary")).click();
        driver.findElement(By.id("addCarBrand")).click();
        WebElement dropdownMenu = driver.findElement(By.id("addCarBrand"));

        Select select = new Select(dropdownMenu);

        select.selectByValue("0: 1");
        driver.findElement(By.id("addCarModel")).click();
        driver.findElement(By.xpath("//select[@id='addCarModel']/option[text()='TT']")).click();
        driver.findElement(By.id("addCarMileage")).sendKeys("123");
        driver.findElement(By.cssSelector(".modal-footer > .btn-primary")).click();
        Thread.sleep(2000);

        driver.findElement(By.className("car_add-expense")).click();
        Thread.sleep(2000);

        WebElement dropdownElement = driver.findElement(By.id("addExpenseCar"));

        WebElement audiTtDrop = dropdownElement.findElement(By.xpath(".//option[text()='Audi TT']"));
        audiTtDrop.click();
        driver.findElement(By.cssSelector("span.icon-calendar")).click();
        WebDriverWait wait = new WebDriverWait(driver, 10);
        WebElement todayDateElement = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn-light.bg-primary.text-white")));
        todayDateElement.click();
        driver.findElement(By.id("addExpenseMileage")).sendKeys("12");
        driver.findElement(By.id("addExpenseLiters")).sendKeys("15");

        driver.findElement(By.id("addExpenseTotalCost")).sendKeys("20");

        driver.findElement(By.xpath("//button[text()='Add']")).click();

        driver.findElement(By.xpath("(//a[contains(text(),'Settings')])[2]")).click();
        driver.findElement(By.xpath("//button[contains(.,'Remove my account')]")).click();
        driver.findElement(By.cssSelector("button.btn.btn-danger")).click();
        Thread.sleep(2000);

    }
}

